### ISSUE TITLE
The training loss is nan in SSD

### ISSUE THREAD

**Issue by 1292765944** [dmlc/gluon-cv#142] opened 2018-05-24 07:55 UTC
I use the default training script (train_ssd.py) to train SSD300, However, the training loss seems to be large and do not converge. The log file is shown below, and what's the problem for this? Thanks!

```
Namespace(batch_size=32, data_shape=300, dataset='voc', epochs=240, gpus='0', log_interval=100, lr=0.001, lr_decay=0.1, lr_decay_epoch='160,200', momentum=0.9, network='vgg16_atrous', num_workers=4, resume='', save_interval=10, save_prefix='ssd_300_vgg16_atrous_voc', seed=233, start_epoch=0, wd=0.0005)
Start training from [Epoch 0]
[Epoch 0][Batch 99], Speed: 31.855627 samples/sec, CrossEntropy=12.250115, SmoothL1=nan
[Epoch 0][Batch 199], Speed: 31.908488 samples/sec, CrossEntropy=12.212773, SmoothL1=nan
[Epoch 0][Batch 299], Speed: 31.279352 samples/sec, CrossEntropy=12.199556, SmoothL1=nan
[Epoch 0][Batch 399], Speed: 30.720933 samples/sec, CrossEntropy=12.192253, SmoothL1=nan
[Epoch 0][Batch 499], Speed: 31.459032 samples/sec, CrossEntropy=12.187363, SmoothL1=nan
[Epoch 0] Training cost: 548.135802, CrossEntropy=12.186622, SmoothL1=nan
[Epoch 0] Validation: 
aeroplane=0.000389
bicycle=0.000102
bird=0.004152
boat=0.000011
bottle=0.000183
bus=0.000084
car=0.000175
cat=0.004419
chair=0.001955
cow=0.000036
diningtable=0.000058
dog=0.001009
horse=0.000108
motorbike=0.005600
person=0.000281
pottedplant=0.000103
sheep=0.000045
sofa=0.000598
train=0.002716
tvmonitor=0.000453
mAP=0.001124
[Epoch 1][Batch 99], Speed: 31.706873 samples/sec, CrossEntropy=12.165724, SmoothL1=nan
```

**Comment by zhreshold** [comment] 2018-05-24 18:52
The smoothl1 is nan at the first batch, suggesting there's some problem. 
What is the mxnet version you use

**Comment by 1292765944** [comment] 2018-05-24 21:47
I use mxnet 1.2.0  version

**Comment by zhreshold** [comment] 2018-05-24 22:55
Just re-run with latest 1.2.0 mxnet, no problem. 
You can self-diagnose it by reduce the --log-interval to 1 and see if the loss is consistantly NaN, if so, there's some problem with your data.

**Comment by 1292765944** [comment] 2018-05-25 03:01
@zhreshold I find that the loss of the first batch seems right. From the second batch on, the loss turns to be nan.
`INFO:root:Namespace(batch_size=32, data_shape=300, dataset='voc', epochs=240, gpus='0,1', log_interval=1, lr=0.001, lr_decay=0.1, lr_decay_epoch='160,200', momentum=0.9, network='vgg16_atrous', num_workers=4, resume='', save_interval=10, save_prefix='ssd_300_vgg16_atrous_voc', seed=233, start_epoch=0, wd=0.0005)
INFO:root:Start training from [Epoch 0]
[10:58:09] src/operator/nn/./cudnn/./cudnn_algoreg-inl.h:107: Running performance tests to find the best convolution algorithm, this can take a while... (setting env variable MXNET_CUDNN_AUTOTUNE_DEFAULT to 0 to disable)
INFO:root:[Epoch 0][Batch 0], Speed: 0.790653 samples/sec, CrossEntropy=19.047861, SmoothL1=3.597861
INFO:root:[Epoch 0][Batch 1], Speed: 41.284082 samples/sec, CrossEntropy=nan, SmoothL1=nan
INFO:root:[Epoch 0][Batch 2], Speed: 31.713405 samples/sec, CrossEntropy=nan, SmoothL1=nan
INFO:root:[Epoch 0][Batch 3], Speed: 25.890616 samples/sec, CrossEntropy=nan, SmoothL1=nan
INFO:root:[Epoch 0][Batch 4], Speed: 28.683838 samples/sec, CrossEntropy=nan, SmoothL1=nan
INFO:root:[Epoch 0][Batch 5], Speed: 33.497645 samples/sec, CrossEntropy=nan, SmoothL1=nan
INFO:root:[Epoch 0][Batch 6], Speed: 38.556546 samples/sec, CrossEntropy=nan, SmoothL1=nan
INFO:root:[Epoch 0][Batch 7], Speed: 33.951709 samples/sec, CrossEntropy=nan, SmoothL1=nan
INFO:root:[Epoch 0][Batch 8], Speed: 23.275500 samples/sec, CrossEntropy=nan, SmoothL1=nan
INFO:root:[Epoch 0][Batch 9], Speed: 7.464060 samples/sec, CrossEntropy=nan, SmoothL1=nan
INFO:root:[Epoch 0][Batch 10], Speed: 38.937492 samples/sec, CrossEntropy=nan, SmoothL1=nan
INFO:root:[Epoch 0][Batch 11], Speed: 37.702319 samples/sec, CrossEntropy=nan, SmoothL1=nan
INFO:root:[Epoch 0][Batch 12], Speed: 22.951652 samples/sec, CrossEntropy=nan, SmoothL1=nan
INFO:root:[Epoch 0][Batch 13], Speed: 16.378508 samples/sec, CrossEntropy=nan, SmoothL1=nan
INFO:root:[Epoch 0][Batch 14], Speed: 10.890180 samples/sec, CrossEntropy=nan, SmoothL1=nan
INFO:root:[Epoch 0][Batch 15], Speed: 38.742375 samples/sec, CrossEntropy=nan, SmoothL1=nan
INFO:root:[Epoch 0][Batch 16], Speed: 31.585562 samples/sec, CrossEntropy=nan, SmoothL1=nan
INFO:root:[Epoch 0][Batch 17], Speed: 6.140043 samples/sec, CrossEntropy=nan, SmoothL1=nan
INFO:root:[Epoch 0][Batch 18], Speed: 21.718652 samples/sec, CrossEntropy=nan, SmoothL1=nan
INFO:root:[Epoch 0][Batch 19], Speed: 27.084998 samples/sec, CrossEntropy=nan, SmoothL1=nan
INFO:root:[Epoch 0][Batch 20], Speed: 37.292782 samples/sec, CrossEntropy=nan, SmoothL1=nan
INFO:root:[Epoch 0][Batch 21], Speed: 8.742909 samples/sec, CrossEntropy=nan, SmoothL1=nan
INFO:root:[Epoch 0][Batch 22], Speed: 11.816909 samples/sec, CrossEntropy=nan, SmoothL1=nan
INFO:root:[Epoch 0][Batch 23], Speed: 22.358796 samples/sec, CrossEntropy=nan, SmoothL1=nan
INFO:root:[Epoch 0][Batch 24], Speed: 35.581926 samples/sec, CrossEntropy=nan, SmoothL1=nan
INFO:root:[Epoch 0][Batch 25], Speed: 5.565665 samples/sec, CrossEntropy=nan, SmoothL1=nan
INFO:root:[Epoch 0][Batch 26], Speed: 14.719581 samples/sec, CrossEntropy=nan, SmoothL1=nan
INFO:root:[Epoch 0][Batch 27], Speed: 28.962313 samples/sec, CrossEntropy=nan, SmoothL1=nan
INFO:root:[Epoch 0][Batch 28], Speed: 38.671024 samples/sec, CrossEntropy=nan, SmoothL1=nan
INFO:root:[Epoch 0][Batch 29], Speed: 19.900063 samples/sec, CrossEntropy=nan, SmoothL1=nan
INFO:root:[Epoch 0][Batch 30], Speed: 12.090345 samples/sec, CrossEntropy=nan, SmoothL1=nan
INFO:root:[Epoch 0][Batch 31], Speed: 39.555740 samples/sec, CrossEntropy=nan, SmoothL1=nan
INFO:root:[Epoch 0][Batch 32], Speed: 17.086560 samples/sec, CrossEntropy=nan, SmoothL1=nan
INFO:root:[Epoch 0][Batch 33], Speed: 15.037508 samples/sec, CrossEntropy=nan, SmoothL1=nan
INFO:root:[Epoch 0][Batch 34], Speed: 10.388879 samples/sec, CrossEntropy=nan, SmoothL1=nan
INFO:root:[Epoch 0][Batch 35], Speed: 25.892713 samples/sec, CrossEntropy=nan, SmoothL1=nan
INFO:root:[Epoch 0][Batch 36], Speed: 14.167316 samples/sec, CrossEntropy=nan, SmoothL1=nan
`

**Comment by zhreshold** [comment] 2018-05-25 17:17
@1292765944 I will investigate this problem. 
Just some question that may or may not relate to this problem, is your GPUs running pretty hot?

**Comment by 1292765944** [comment] 2018-05-26 02:45
@zhreshold I think the gpu is ok. Maxwell TITANX is used in my experiments. The running temp is 85C, and the idle temp is 55C (obtained by nvidia-smi).
I also find that if two gpus is adopted for training, the training loss is worse than one gpu and the loss becomes nan immediately after one batch training.
Before using gluoncv, I also try your old mxnet-ssd project. This project works well but the accuracy is a little lower than caffe, but the training efficiency is far better than caffe and the training time is much shorter. So I'd appreciate for your help.

**Comment by 1292765944** [comment] 2018-05-28 15:58
@zhreshold Could you reproduce my error? So where's the problem for this error? Is it the model initialization problem?

**Comment by zhreshold** [comment] 2018-05-28 23:11
I tried multiple times on ec2, cannot reproduce the error yet. Since you are getting exploding loss after first update, I suspect your pretrained model or initialized tail are abnormal. Let me think where could possibly go wrong.

**Comment by 1292765944** [comment] 2018-06-07 12:32
@zhreshold  any ideas for this problem?

**Comment by zhreshold** [comment] 2018-06-07 23:46
@1292765944 Try remove related pretrained models in ~/.mxnet/models and update mxnet/gluon-cv, run with default parameters again?

**Comment by Intellige** [comment] 2018-06-14 12:39
Hello,
We used the file: gluon-cv/scripts/detection/ssd/train_ssd.py.  MXnetcu80 version 1.3.0
1 When we used the COCO datasets, we had the Nan problem as the same as @1292765944 provided.
 we ran : python train_ssd.py --gpus 0,1 --dataset coco --network vgg16_atrous --data-shape 300
 the result: INFO:root:[Epoch 0][Batch 99], Speed: 65.487 samples/sec, CrossEntropy=17.562, SmoothL1=nan . 
2 While we used the VOC datesets, even though CrossEntropy and SmoothLy were normal，in the validation step，The last mAP was poorly low，around 0.002 in the first epoch, and,smaller lr did not work.

We have reinstalled  mxnet and reloaded initial paras,but don't work ~~~

**Comment by zhreshold** [comment] 2018-06-14 18:20
We fixed a minor problem with coco, so the behavior of coco is confirmed. 
However, for the VOC datasets, it is very weird that people are getting all kinds of different problems during training. I have repeated multiple times, all going pretty smoothly.

I will try some instances with CUDA80 and latest mxnet, please let me know if you guys have new findings.

**Comment by zqburde** [comment] 2018-07-02 09:51
First I also encounter this problem, decreasing the lr is my solution.

**Comment by 1292765944** [comment] 2018-07-02 12:18
@zqburde How did you set the lr? Does it hurt the final mAP?

**Comment by zqburde** [comment] 2018-07-03 07:49
@1292765944 I set the lr 0.001 to 0.0008 and increase the epochs, it doesn't influence the final mAP.

**Comment by Wallart** [comment] 2018-07-15 13:52
I am working with a GTX 1080Ti and I had the same issue on the previous gluoncv release (0.1), the loss was rapidly going to nan. Unfortunately I can no longer reproduce on gluoncv 0.2.

For better understanding I also implemented my own SSD inspired by amdegroot 's ssd.pytorch and had no issues. Then I tried to improve my implementation using some gluoncv concept and the training loss was nan too. In my experiments it's linked to : 
self.init = {
            'weight_initializer': Xavier(
                rnd_type='gaussian', factor_type='out', magnitude=2),
            'bias_initializer': 'zeros'
}

Used in VGGAtrousBase class. Removing this initializer solved my nan issue.
Hope it helps.

**Comment by Angzz** [comment] 2018-08-09 14:40
When I train ssd with coco, the training curve seems nomal, but when validation, the AP[0.5:0.95] is always nearly zero, so what's the problem maybe?

this is my params setting :
Namespace(batch_size=16, data_shape=512, dataset='coco', epochs=240, gpus='0,1', log_interval=100, lr=0.001, lr_decay=0.1, lr_decay_epoch='160,200', momentum=0.9, network='resnet50_v1', num_workers=4, resume='', save_interval=1, save_prefix='ssd_512_resnet50_v1_coco', seed=233, start_epoch=0, val_interval=1, wd=0.0005)

this is my training curve:
[Epoch 9][Batch 4799], Speed: 53.161 samples/sec, CrossEntropy=3.285, SmoothL1=3.270
[Epoch 9][Batch 4899], Speed: 54.386 samples/sec, CrossEntropy=3.285, SmoothL1=3.274
[Epoch 9][Batch 4999], Speed: 58.573 samples/sec, CrossEntropy=3.285, SmoothL1=3.275
[Epoch 9][Batch 5099], Speed: 55.887 samples/sec, CrossEntropy=3.285, SmoothL1=3.274
[Epoch 9][Batch 5199], Speed: 54.713 samples/sec, CrossEntropy=3.285, SmoothL1=3.275
[Epoch 9][Batch 5299], Speed: 41.466 samples/sec, CrossEntropy=3.284, SmoothL1=3.276
[Epoch 9][Batch 5399], Speed: 53.258 samples/sec, CrossEntropy=3.283, SmoothL1=3.278
[Epoch 9][Batch 5499], Speed: 57.705 samples/sec, CrossEntropy=3.283, SmoothL1=3.279
[Epoch 9][Batch 5599], Speed: 56.832 samples/sec, CrossEntropy=3.283, SmoothL1=3.279
[Epoch 9][Batch 5699], Speed: 54.667 samples/sec, CrossEntropy=3.284, SmoothL1=3.280
[Epoch 9][Batch 5799], Speed: 53.720 samples/sec, CrossEntropy=3.285, SmoothL1=3.278
[Epoch 9][Batch 5899], Speed: 32.793 samples/sec, CrossEntropy=3.285, SmoothL1=3.279
[Epoch 9][Batch 5999], Speed: 57.327 samples/sec, CrossEntropy=3.286, SmoothL1=3.282
[Epoch 9][Batch 6099], Speed: 40.294 samples/sec, CrossEntropy=3.286, SmoothL1=3.281
[Epoch 9][Batch 6199], Speed: 55.066 samples/sec, CrossEntropy=3.286, SmoothL1=3.283
[Epoch 9][Batch 6299], Speed: 56.626 samples/sec, CrossEntropy=3.285, SmoothL1=3.281
[Epoch 9][Batch 6399], Speed: 54.353 samples/sec, CrossEntropy=3.285, SmoothL1=3.282
[Epoch 9][Batch 6499], Speed: 27.371 samples/sec, CrossEntropy=3.284, SmoothL1=3.284
[Epoch 9][Batch 6599], Speed: 38.576 samples/sec, CrossEntropy=3.284, SmoothL1=3.286
[Epoch 9][Batch 6699], Speed: 36.140 samples/sec, CrossEntropy=3.283, SmoothL1=3.286
[Epoch 9][Batch 6799], Speed: 14.973 samples/sec, CrossEntropy=3.283, SmoothL1=3.285
[Epoch 9][Batch 6899], Speed: 56.728 samples/sec, CrossEntropy=3.284, SmoothL1=3.283
[Epoch 9][Batch 6999], Speed: 56.083 samples/sec, CrossEntropy=3.284, SmoothL1=3.281
[Epoch 9][Batch 7099], Speed: 53.444 samples/sec, CrossEntropy=3.283, SmoothL1=3.280
[Epoch 9][Batch 7199], Speed: 19.701 samples/sec, CrossEntropy=3.283, SmoothL1=3.281
[Epoch 9][Batch 7299], Speed: 55.817 samples/sec, CrossEntropy=3.283, SmoothL1=3.279
[Epoch 9] Training cost: 3115.671, CrossEntropy=3.283, SmoothL1=3.279
[Epoch 9] Validation:
~~~~ Summary metrics ~~~~
=Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.001
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.001
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.003
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.002
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.003
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.003
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.001
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.006

So Why, I use the newest pre version of gluoncv without any modification. and mxnet is also the pre version, my gpu is TITAXp(12G). Can you give me some suggestions? @zhreshold

**Comment by zhreshold** [comment] 2018-08-09 18:59
What I got after one epoch with python3 ../gluon-cv/scripts/detection/ssd/train_ssd.py --gpus 0,1,2,3 -j 32 --network vgg16_atrous --data-shape 300 --dataset coco --lr 0.001 --lr-decay-epoch 160,200 --lr-decay 0.1 --epochs 240

```
~~~~ Summary metrics ~~~~
=Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.019
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.048
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.010
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.004
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.020
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.028
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.038
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.058
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.063
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.013
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.053
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.083
```

**Comment by Angzz** [comment] 2018-08-10 00:57
totady I find when train with python3, everything is ok, but not ok with python2, can you have a try? @zhreshold

**Comment by zhreshold** [comment] 2018-08-10 01:00
@Angzz So, now you remind me of this thread https://github.com/dmlc/gluon-cv/issues/195
Yes, it is a known bug for division on python2.

**Comment by Angzz** [comment] 2018-08-10 01:02
@zhreshold OK, I will turn the orig_height and orig_width into float and have a try, thanks!!

**Comment by LeeRel1991** [comment] 2018-10-16 09:48
Hi,all. Recently I also encounter such problem（loss=nan）. Specifically, when i train **ssd512_vgg16_atrous on GTX1080 for face detecttion**, the batchsize=8, both SmoothL1Loss and  CrossEntropy are nan always. Then i comment the line net.hybridize() in train function and validate function, the loss become  normal and the success. Finally i change the batchsize from 8 to 16 and lr from 0.001 to 0.00001 under net.hybridize() on voc2012 and seld-designed dataset, the find out the followings:
batchsize >=12 GTX1080 will out of memory, 
batchsize=10 the train is normal, 
batchsize<=8 the loss is easy to nan.

so the conclusion may be that small batchsize tend to output nan loss when using net.hybridize(), the possible solution is comment is or change large batchsize if the gpu support.  Or, you can change **ssd300_vgg16** on which gtx1080 also support batchsize>=16
Hope to helps.

**Comment by Feywell** [comment] 2018-10-30 09:32
I encounter the same question.
How can i fix it?
environment:

centos 6.4
python 3.5
mxnet-cuda80 1.3.0
gluoncv 0.3.0
gpu tesla k20 * 2

command:
`train_ssd.py --batch-size 32 --num-workers 4 --gpus 0,1 --log-interval 1 --epochs 20`
result:

> /home/liyang/anaconda2/envs/gluon/lib/python3.5/site-packages/mxnet/gluon/block.py:421: UserWarning: load_params is deprecated. Please use load_parameters.
  warnings.warn("load_params is deprecated. Please use load_parameters.")
INFO:root:Namespace(batch_size=32, data_shape=300, dataset='voc', epochs=20, gpus='0,1', log_interval=1, lr=0.001, lr_decay=0.1, lr_decay_epoch='160,200', momentum=0.9, network='vgg16_atrous', num_workers=4, resume='', save_interval=10, save_prefix='ssd_300_vgg16_atrous_voc', seed=233, start_epoch=0, val_interval=1, wd=0.0005)
INFO:root:Start training from [Epoch 0]
INFO:root:[Epoch 0][Batch 0], Speed: 1.764 samples/sec, CrossEntropy=19.147, SmoothL1=3.899
INFO:root:[Epoch 0][Batch 1], Speed: 24.210 samples/sec, CrossEntropy=2911234189311495764698741583380480.000, SmoothL1=nan
INFO:root:[Epoch 0][Batch 2], Speed: 24.310 samples/sec, CrossEntropy=1940822792874330605875953106157568.000, SmoothL1=nan
INFO:root:[Epoch 0][Batch 3], Speed: 24.335 samples/sec, CrossEntropy=1455617094655747882349370791690240.000, SmoothL1=nan
INFO:root:[Epoch 0][Batch 4], Speed: 24.308 samples/sec, CrossEntropy=1164493675724598305879496633352192.000, SmoothL1=nan
INFO:root:[Epoch 0][Batch 5], Speed: 24.310 samples/sec, CrossEntropy=970411396437165302937976553078784.000, SmoothL1=nan
INFO:root:[Epoch 0][Batch 6], Speed: 24.105 samples/sec, CrossEntropy=831781196946141647056783309537280.000, SmoothL1=nan
INFO:root:[Epoch 0][Batch 7], Speed: 24.253 samples/sec, CrossEntropy=727808547327873941174685395845120.000, SmoothL1=nan
INFO:root:[Epoch 0][Batch 8], Speed: 23.193 samples/sec, CrossEntropy=646940930958110201958651035385856.000, SmoothL1=nan
INFO:root:[Epoch 0][Batch 9], Speed: 24.274 samples/sec, CrossEntropy=582246837862299152939748316676096.000, SmoothL1=nan
INFO:root:[Epoch 0][Batch 10], Speed: 24.294 samples/sec, CrossEntropy=529315307147544684490680287887360.000, SmoothL1=nan
INFO:root:[Epoch 0][Batch 11], Speed: 24.299 samples/sec, CrossEntropy=485205698218582651468988276539392.000, SmoothL1=nan
INFO:root:[Epoch 0][Batch 12], Speed: 24.254 samples/sec, CrossEntropy=447882182970999315157839918399488.000, SmoothL1=nan
INFO:root:[Epoch 0][Batch 13], Speed: 24.282 samples/sec, CrossEntropy=415890598473070823528391654768640.000, SmoothL1=nan
INFO:root:[Epoch 0][Batch 14], Speed: 24.254 samples/sec, CrossEntropy=388164558574866077940634198474752.000, SmoothL1=nan
INFO:root:[Epoch 0][Batch 15], Speed: 24.311 samples/sec, CrossEntropy=363904273663936970587342697922560.000, SmoothL1=nan
INFO:root:[Epoch 0][Batch 16], Speed: 24.316 samples/sec, CrossEntropy=342498139918999489013217708998656.000, SmoothL1=nan
INFO:root:[Epoch 0][Batch 17], Speed: 24.265 samples/sec, CrossEntropy=323470465479055100979325517692928.000, SmoothL1=nan
INFO:root:[Epoch 0][Batch 18], Speed: 23.947 samples/sec, CrossEntropy=306445704138052197135277120028672.000, SmoothL1=nan
INFO:root:[Epoch 0][Batch 19], Speed: 24.302 samples/sec, CrossEntropy=291123418931149576469874158338048.000, SmoothL1=nan
INFO:root:[Epoch 0][Batch 20], Speed: 24.317 samples/sec, CrossEntropy=277260398982047203675995430191104.000, SmoothL1=nan
INFO:root:[Epoch 0][Batch 21], Speed: 24.300 samples/sec, CrossEntropy=264657653573772342245340143943680.000, SmoothL1=nan
INFO:root:[Epoch 0][Batch 22], Speed: 24.208 samples/sec, CrossEntropy=253150799070564836572482913697792.000, SmoothL1=nan
INFO:root:[Epoch 0][Batch 23], Speed: 24.297 samples/sec, CrossEntropy=242602849109291325734494138269696.000, SmoothL1=nan
INFO:root:[Epoch 0][Batch 24], Speed: 24.015 samples/sec, CrossEntropy=232898735144919668381658730463232.000, SmoothL1=nan
INFO:root:[Epoch 0][Batch 25], Speed: 24.267 samples/sec, CrossEntropy=223941091485499657578919959199744.000, SmoothL1=nan
INFO:root:[Epoch 0][Batch 26], Speed: 24.300 samples/sec, CrossEntropy=215646976986036709967018999152640.000, SmoothL1=nan
INFO:root:[Epoch 0][Batch 27], Speed: 24.314 samples/sec, CrossEntropy=207945299236535411764195827384320.000, SmoothL1=nan
INFO:root:[Epoch 0][Batch 28], Speed: 24.298 samples/sec, CrossEntropy=200774771676654886535912698675200.000, SmoothL1=nan
INFO:root:[Epoch 0][Batch 29], Speed: 24.240 samples/sec, CrossEntropy=194082279287433038970317099237376.000, SmoothL1=nan
INFO:root:[Epoch 0][Batch 30], Speed: 24.287 samples/sec, CrossEntropy=187821560600741678509698110717952.000, SmoothL1=nan
INFO:root:[Epoch 0][Batch 31], Speed: 24.331 samples/sec, CrossEntropy=181952136831968485293671348961280.000, SmoothL1=nan
INFO:root:[Epoch 0][Batch 32], Speed: 24.310 samples/sec, CrossEntropy=176438435715848240173159102283776.000, SmoothL1=nan
INFO:root:[Epoch 0][Batch 33], Speed: 24.337 samples/sec, CrossEntropy=171249069959499744506608854499328.000, SmoothL1=nan
INFO:root:[Epoch 0][Batch 34], Speed: 24.368 samples/sec, CrossEntropy=166356239389228329411356661907456.000, SmoothL1=nan
INFO:root:[Epoch 0][Batch 35], Speed: 24.338 samples/sec, CrossEntropy=161735232739527550489662758846464.000, SmoothL1=nan

**Comment by zhreshold** [comment] 2018-10-30 18:00
@Feywell Try reduce lr slightly with ``--lr 0.0005`` for example.

**Comment by jacky4323** [comment] 2018-12-12 04:48
Hi,
I have tested different batch-size, Why larger batch-size will get nan loss?
And also I test three command below ,2nd and 3th use same batch but get NaN in 3th training.

1st :python3 train_ssd.py --batch-size 12 --num-workers 10 --gpus 0 --log-interval 1  --lr 0.0005
2nd:python3 train_ssd.py --batch-size 8--num-workers 10 --gpus 0 --log-interval 1  --lr 0.0005
3th :python3 train_ssd.py --batch-size 8--num-workers 10 --gpus 0 --log-interval 1  --lr 0.0005


python3 train_ssd.py --batch-size 12 --num-workers 10 --gpus 0 --log-interval 1  --lr 0.0005

> INFO:root:[Epoch 0][Batch 0], Speed: 2.745 samples/sec, CrossEntropy=19.230, SmoothL1=3.947
> INFO:root:[Epoch 0][Batch 1], Speed: 10.406 samples/sec, CrossEntropy=nan, SmoothL1=nan
> INFO:root:[Epoch 0][Batch 1], Speed: 10.406 samples/sec, CrossEntropy=nan, SmoothL1=nan
> INFO:root:[Epoch 0][Batch 1], Speed: 10.406 samples/sec, CrossEntropy=nan, SmoothL1=nan

python3 train_ssd.py --batch-size 8--num-workers 10 --gpus 0 --log-interval 1  --lr 0.0005

> INFO:root:[Epoch 0][Batch 0], Speed: 2.362 samples/sec, CrossEntropy=18.623, SmoothL1=4.061
> INFO:root:[Epoch 0][Batch 1], Speed: 10.102 samples/sec, CrossEntropy=nan, SmoothL1=nan
> INFO:root:[Epoch 0][Batch 2], Speed: 10.230 samples/sec, CrossEntropy=nan, SmoothL1=nan
> INFO:root:[Epoch 0][Batch 3], Speed: 10.214 samples/sec, CrossEntropy=nan, SmoothL1=nan
> INFO:root:[Epoch 0][Batch 4], Speed: 10.209 samples/sec, CrossEntropy=nan, SmoothL1=nan
> INFO:root:[Epoch 0][Batch 5], Speed: 10.219 samples/sec, CrossEntropy=nan, SmoothL1=nan
> INFO:root:[Epoch 0][Batch 6], Speed: 10.218 samples/sec, CrossEntropy=nan, SmoothL1=nan
> INFO:root:[Epoch 0][Batch 7], Speed: 10.201 samples/sec, CrossEntropy=nan, SmoothL1=nan


python3 train_ssd.py --batch-size 8--num-workers 10 --gpus 0 --log-interval 1  --lr 0.0005

> INFO:root:Start training from [Epoch 0]
> INFO:root:[Epoch 0][Batch 0], Speed: 1.939 samples/sec, CrossEntropy=18.577, SmoothL1=3.817
> INFO:root:[Epoch 0][Batch 1], Speed: 10.114 samples/sec, CrossEntropy=18.320, SmoothL1=3.906
> INFO:root:[Epoch 0][Batch 2], Speed: 10.197 samples/sec, CrossEntropy=18.193, SmoothL1=4.051
> INFO:root:[Epoch 0][Batch 3], Speed: 10.168 samples/sec, CrossEntropy=17.870, SmoothL1=3.842
> INFO:root:[Epoch 0][Batch 4], Speed: 10.158 samples/sec, CrossEntropy=17.454, SmoothL1=4.076
> INFO:root:[Epoch 0][Batch 5], Speed: 10.179 samples/sec, CrossEntropy=16.981, SmoothL1=3.938
> INFO:root:[Epoch 0][Batch 6], Speed: 10.168 samples/sec, CrossEntropy=16.503, SmoothL1=3.988
> INFO:root:[Epoch 0][Batch 7], Speed: 10.134 samples/sec, CrossEntropy=16.100, SmoothL1=3.868

**Comment by FishYuLi** [comment] 2019-01-14 02:50
@Intellige Have you solved the problem? How?

Hello, I got a similar problem.
The environment: cuda8.0 mxnet1.5.0 python2.7 (I don't have sudo permission to update the gpu driver...)
I run exactly the same shell script as the [provided one](https://raw.githubusercontent.com/dmlc/web-data/master/gluoncv/logs/detection/ssd_512_resnet50_v1_voc.sh).
The losses are pretty large at first, lager than the [provided log](https://raw.githubusercontent.com/dmlc/web-data/master/gluoncv/logs/detection/ssd_512_resnet50_v1_voc_train.log), but the validation mAP is really poor. (Shown as follows)
![ssd1](https://ws3.sinaimg.cn/large/006tNc79ly1fz5x2w1padj31hc0u047n.jpg)
The cross entropy loss converges normally, but the SmoothL1 does not converge, and the validation mAP is still very bad after 20 epochs. (Shown as follows)
![ssd2](https://ws2.sinaimg.cn/large/006tNc79ly1fz5x5aw206j31hc0u0450.jpg)

@zhreshold Any possible suggestions?

**Comment by Intellige** [comment] 2019-01-24 16:44
Hi,sorry so late to answer the question.
When I encountered the question, I had tried to change the versions of MXNET and cuda . Of course
I also tried some suggestions above.
However, I wasn't lucky. at last, I reinstalled the UBUNTU, cuda and so on, they were all the same as I faced the questions.  It really works. I don't know why..

**Comment by FishYuLi** [comment] 2019-01-25 05:52
@Intellige Thanks. It's really confusing...

**Comment by zhreshold** [comment] 2019-01-25 18:52
please reduce learning rate a little bit in case you meet sudden `nan` problems, I have some feedbacks says that reduce lr to half can solve nan problem in some cases.

**Comment by zhreshold** [comment] 2019-03-07 08:00
Just an update, the root cause is found and fix has been merged to master: https://github.com/apache/incubator-mxnet/pull/14209

By using master/nightly built pip package hopefully you won't meet same problem any more

**Closed** 2019-03-07 08:01 UTC
