### ISSUE TITLE
Yolo3 dataloader for custom data kernel dies.

### ISSUE THREAD

**Issue by djaym7** [dmlc/gluon-cv#1070] opened 2019-12-02 21:27 UTC
classes = [ '1', '2', '3']
kernel dies
classes = [ '1', '2', '3', '4'] - works fine

Actual number of classes = 3 and works for ssd data loader perfectly.. idk why yolo3's loader required one more class (Isn't the background class added by default?). Tried on mxnet 1.4.1 , 1.5.0 and 1.6.0

Here is the code for yolo's and ssd's data loader.

![image](https://user-images.githubusercontent.com/12378820/69996699-6dd74400-1507-11ea-9f20-4cc6a2232dea.png)

**Comment by djaym7** [comment] 2019-12-02 21:29
@zhreshold  any idea why the kernel dies ?

**Comment by zhreshold** [comment] 2019-12-02 21:31
It might be something else, the number of classes should be 3 no matter what.

Can you show me the kernel fail log?

**Comment by djaym7** [comment] 2019-12-02 22:07
#restart and run all on jupyter notebook
[I 22:06:37.142 NotebookApp] Kernel restarted: 8be9212c-8f04-4f09-817c-026d5cbecb5c
[W 22:06:38.026 NotebookApp] No session ID specified
[I 22:06:38.026 NotebookApp] Adapting to protocol v5.1 for kernel 8be9212c-8f04-4f09-817c-026d5cbecb5c
[I 22:06:38.027 NotebookApp] Discarding 6 buffered messages for 8be9212c-8f04-4f09-817c-026d5cbecb5c:0c9b7d3e-0bf6a709d58b87a8d19a1f0e
terminate called after throwing an instance of 'dmlc::Error'
  what():  [22:06:50] src/ndarray/ndarray.cc:641: Check failed: !is_view:

**Comment by djaym7** [comment] 2019-12-02 22:22
UPDATE:
Something is wrong with mkl, installed mxnet-cu101 and it worked but not working in mxnet-cu101mkl. Report bug somewhere in mkl. Thanks

**Comment by zhreshold** [comment] 2019-12-02 22:28
@djaym7 Good to know. 

@pengzhao-intel @xinyu-intel  FYI, this seems to be related to mkl versions only.

**Comment by xinyu-intel** [comment] 2019-12-26 03:25
@wuxun-zhang pls help take a look at this issue. thx:)

**Comment by wuxun-zhang** [comment] 2020-01-01 04:24
@djaym7 Any update for this issue? Could you also share the script/dataset to reproduce? Thanks.

**Comment by djaym7** [comment] 2020-01-17 22:07
Currently on hold, will try the path once i am back on it. Thanks

**Comment by zhreshold** [comment] 2020-02-19 18:48
@wuxun-zhang I got another report pointing to this error again. It's affecting the latest SageMaker + mxnet 1.6.0 for training, do you have plan to add this fix to mxnet?

**Comment by wuxun-zhang** [comment] 2020-02-20 02:44
@zhreshold You mean the above [patch](https://github.com/wuxun-zhang/incubator-mxnet/commit/e9f5c663b03c3e8f4463c32ba2b1cb2aa47986a4) can resolve this issue? If so, I will submit a PR to mxnet soon.

**Comment by zhreshold** [comment] 2020-02-20 05:27
@wuxun-zhang It's not verified yet, I will try to make a minimal reproducible code for you

**Comment by djaym7** [comment] 2020-02-21 22:11
You can just use custom data (i cant share the one i have here) and when you try to initiate dataloader function kernel dies when using mkldnn.

**Comment by wuxun-zhang** [comment] 2020-02-24 08:36
@djaym7 @zhreshold  Thanks. I will try to reproduce this issue first. Will let you know if there is any update.

**Comment by wuxun-zhang** [comment] 2020-02-25 03:01
I am using the MXNet master (commit a6ab49f27446bcc858a14fab0e63dd1959d456cc). 

**1. Prepare custom dataset** (refer to [detection_custom.py](https://gluon-cv.mxnet.io/_downloads/f9e86d9a33ef8e8c824a66e272e6ea93/detection_custom.py) ).
```
import os, zipfile
from gluoncv import utils
import mxnet as mx
import numpy as np

dog_label = [130, 220, 320, 530]
car_label = [480, 80, 700, 170]

all_boxes = np.array([dog_label, car_label])
all_ids = np.array([0, 1])
class_names = ['dog', 'car']

def write_line(img_path, im_shape, boxes, ids, idx):
    h, w, c = im_shape
    # for header, we use minimal length 2, plus width and height
    # with A: 4, B: 5, C: width, D: height
    A = 4
    B = 5
    C = w
    D = h
    # concat id and bboxes
    labels = np.hstack((ids.reshape(-1, 1), boxes)).astype('float')
    # normalized bboxes (recommanded)
    labels[:, (1, 3)] /= float(w)
    labels[:, (2, 4)] /= float(h)
    # flatten
    labels = labels.flatten().tolist()
    str_idx = [str(idx)]
    str_header = [str(x) for x in [A, B, C, D]]
    str_labels = [str(x) for x in labels]
    str_path = [img_path]
    line = '\t'.join(str_idx + str_header + str_labels + str_path) + '\n'
    return line

with open('train.lst', 'w') as fw:
    for i in range(4):
        line = write_line('test.jpg', img.shape, all_boxes, all_ids, i)
        print(line)
        fw.write(line)
```

**2. Running test script**:
```
import mxnet as mx
from mxnet import gluon
import gluoncv as gcv
import os,random,warnings,logging,time
warnings.simplefilter("ignore")
import numpy as np
from gluoncv.data.batchify import Tuple, Stack, Pad
from gluoncv.data.transforms.presets.yolo import YOLO3DefaultTrainTransform
from gluoncv.data import LstDetection
from gluoncv.data.transforms.presets.yolo import YOLO3DefaultValTransform
ctx = [mx.gpu(i) for i in range(mx.context.num_gpus())] #doesnt matter since dataloader uses cpu workers
categories = ['dog', 'car']

def get_dataloader(net, train_dataset, val_dataset, data_shape=608, batch_size=5, num_workers=15):
    if train_dataset is not None:
        width, height = data_shape, data_shape

        batchify_fn = Tuple(*([Stack() for _ in range(6)] + [Pad(axis=0, pad_val=-1) for _ in range(1)]))  # stack image, all targets generated
        train_loader = mx.gluon.data.DataLoader(
                            train_dataset.transform(YOLO3DefaultTrainTransform(width, height, net,mixup=False)),
                            batch_size, True, batchify_fn=batchify_fn, last_batch='rollover', num_workers=num_workers)

        val_batchify_fn = Tuple(Stack(), Pad(pad_val=-1))
        val_loader = mx.gluon.data.DataLoader(val_dataset.transform(YOLO3DefaultValTransform(width, height)),
                        batch_size, False, batchify_fn=val_batchify_fn, last_batch='keep', num_workers=num_workers)
        return train_loader, val_loader

net = gcv.model_zoo.yolo3_darknet53_coco(pretrained=True)
net.reset_class(categories)
from gluoncv.data import LstDetection
train_dataset = LstDetection('train.lst', root=os.path.expanduser('.'))
test_dataset = LstDetection('val.lst', root=os.path.expanduser('.'))
print(len(train_dataset),len(test_dataset))
train_loader,val_loader = get_dataloader(net, train_dataset, test_dataset, batch_size=2, num_workers=20) #dies

for i, batch in enumerate(train_loader):
    print(i, batch[0].shape, batch[1].shape)
```

**Output is like below**:
```
4 4
0 (2, 3, 608, 608) (2, 22743, 1)
1 (2, 3, 608, 608) (2, 22743, 1)
```

I cannot reproduce this issue with the above dataset and script. Please correct me if I am missing anything. Thanks. @djaym7

**Comment by zhreshold** [comment] 2020-02-25 18:45
@wuxun-zhang It has to be 3 classes

**Comment by wuxun-zhang** [comment] 2020-02-26 02:54
> @wuxun-zhang It has to be 3 classes

Thanks. Now I can reproduce with 3 classes.
Please try [this patch](https://github.com/apache/incubator-mxnet/pull/17689) and see if this issue is resolved? Thanks

**Comment by wuxun-zhang** [comment] 2020-02-29 13:30
The patch has been already merged into mxnet master. Can we close this issue now?

**Comment by zhreshold** [comment] 2020-02-29 23:50
Closing this now, let me know if the error persists

**Closed by zhreshold** 2020-02-29 23:50 UTC
