### ISSUE TITLE
GluonCV with CUDA 9.1, pandas and OpenCV: numpy error

### ISSUE THREAD

**Issue by LewsTherin511** [dmlc/gluon-cv#1061] opened 2019-11-27 13:27 UTC
I'm trying to install GluonCV with GPU support in a conda environment.

To check with CUDA version I have (it's a server I'm accessing through ssh, so it was installed already), I ran:

`nvcc --version`

and got:

```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Fri_Nov__3_21:07:56_CDT_2017
Cuda compilation tools, release 9.1, V9.1.85
```

So I installed Gluon with:

`pip install --upgrade mxnet-cu91mkl gluoncv`

and, since I also need pandas and opencv, I ran:

```
conda install -c anaconda pandas
conda install -c anaconda opencv
```
Everything fine so far, but whenever I try to run some code (a script to generate .lst files, so it's not even actually using the GPU) I got an error message stating there is an issue with the numpy installation:

`ImportError: Something is wrong with the numpy installation. While importing we detected an older version of numpy in ['/home/carlo/.conda/envs/gluon/lib/python3.7/site-packages/numpy']. One method of fixing this is to repeatedly uninstall numpy until none is found, then reinstall this version.`

I tried in environments created either with support for Python 3.6 and 3.7, but it didn't work in either way. Any idea on how to fix it?

-------------------------------
**EDIT:**
-------------------------------
Fixed it, basically, all I had to do was:
```
pip install --upgrade mxnet-cu90mkl gluoncv
conda install -c anaconda cudatoolkit==9.0
```

So, it seems I was using the wrong version of mxnet-cuXXmkl, and I was missing the cudatoolkit in my environment.

**Comment by bryanyzhu** [comment] 2019-12-06 00:19
It seems the problem is fixed. Thank you for posting the solution here, I will close the issue later.

**Closed** 2019-12-08 03:11 UTC
