### ISSUE TITLE
About the target.py and rpn_target.py

### ISSUE THREAD

**Issue by Angzz** [dmlc/gluon-cv#193] opened 2018-07-04 16:35 UTC
Hi, I find the SSDTargetGenerator defined in nn/ssd/target.py not used over all the gluoncv, the same question in nn/rpn/rpn_target.py. So what's the reason, do you consider the ``gluon.Block`` will slow down the training process and use completely hybrid/symbol? Or you have any other plan to put it into use in the next version?

**Comment by Angzz** [comment] 2018-07-05 03:40
I find it used in the transform, sorry......

**Comment by zhreshold** [comment] 2018-07-06 22:50
As the problem is discussed in forum, I am closing this.

**Closed by zhreshold** 2018-07-06 22:50 UTC
